before_install:
  - sudo apt-get install -y g++
  - sudo apt-get install -y liblz4-dev
  - sudo apt-get install -y dpkg
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu bionic universe" -y
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu bionic main" -y
  - sudo apt-get update -q
  - sudo apt-get install -y capnproto
language: rust
rust:
  - nightly
cache: cargo
script:
- cargo test --all-features
- cargo check --bench basic
notifications:
  email:
    on_success: never
