#!/bin/bash
set -eu

check_char='\xE2\x9C\x93'
cross_char='\xE2\x9D\x8C'
green='\033[0;32m'
nc='\033[0m'
check="$green$check_char$nc"
cross="$green$cross_char$nc"
errors=0

: '
echo -n "Checking formatting... "
diff=$(cargo fmt -- --write-mode diff)
stripped_diff=$(echo "$diff" | sed -e '/^Diff of/d' -e '/^$/d')

if [ -z "$stripped_diff" ]; then
	echo -e "$check"
else
	echo -e "$cross"
	echo "$diff"
	errors=1
fi
'

echo -n "Running tests... "
if result=$(cargo +nightly test --color always 2>&1); then
	echo -e "$check"
else
	echo -e "$cross"
	echo "$result"
	errors=1
fi

echo -n "Compiling benchmarks... "
if result=$(cargo +nightly check --bench basic --color always 2>&1); then
	echo -e "$check"
else
	echo -e "$cross"
	echo "$result"
	errors=1
fi


if [ "$errors" != 0 ]; then
	echo "Failed"
	exit 1
else
	echo "OK"
fi
