use extractor;


pub fn nyc_colnames() -> Vec<String> {
    vec![
        "trip_id".to_string(),
        "vendor_id".to_string(),
        "pickup_datetime".to_string(),
        "dropoff_datetime".to_string(),
        "store_and_fwd_flag".to_string(),
        "rate_code_id".to_string(),
        "pickup_longitude".to_string(),
        "pickup_latitude".to_string(),
        "dropoff_longitude".to_string(),
        "dropoff_latitude".to_string(),
        "passenger_count".to_string(),
        "trip_distance".to_string(),
        "fare_amount".to_string(),
        "extra".to_string(),
        "mta_tax".to_string(),
        "tip_amount".to_string(),
        "tolls_amount".to_string(),
        "ehail_fee".to_string(),
        "improvement_surcharge".to_string(),
        "total_amount".to_string(),
        "payment_type".to_string(),
        "trip_type".to_string(),
        "pickup".to_string(),
        "dropoff".to_string(),
        "cab_type".to_string(),
        "precipitation".to_string(),
        "snow_depth".to_string(),
        "snowfall".to_string(),
        "max_temperature".to_string(),
        "min_temperature".to_string(),
        "average_wind_speed".to_string(),
        "pickup_nyct2010_gid".to_string(),
        "pickup_ctlabel".to_string(),
        "pickup_borocode".to_string(),
        "pickup_boroname".to_string(),
        "pickup_ct2010".to_string(),
        "pickup_boroct2010".to_string(),
        "pickup_cdeligibil".to_string(),
        "pickup_ntacode".to_string(),
        "pickup_ntaname".to_string(),
        "pickup_puma".to_string(),
        "dropoff_nyct2010_gid".to_string(),
        "dropoff_ctlabel".to_string(),
        "dropoff_borocode".to_string(),
        "dropoff_boroname".to_string(),
        "dropoff_ct2010".to_string(),
        "dropoff_boroct2010".to_string(),
        "dropoff_cdeligibil".to_string(),
        "dropoff_ntacode".to_string(),
        "dropoff_ntaname".to_string(),
        "dropoff_puma".to_string(),
    ]
}

pub fn nyc_extractors() -> Vec<(String, extractor::Extractor)> {
    vec![
        ("pickup_datetime".to_owned(), extractor::date_time),
        ("dropoff_datetime".to_owned(), extractor::date_time),
        ("pickup_longitude".to_owned(), extractor::multiply_by_1000),
        ("pickup_latitude".to_owned(), extractor::multiply_by_1000),
        ("dropoff_longitude".to_owned(), extractor::multiply_by_1000),
        ("dropoff_latitude".to_owned(), extractor::multiply_by_1000),
        ("trip_distance".to_owned(), extractor::multiply_by_1000),
        ("fare_amount".to_owned(), extractor::multiply_by_100),
        ("extra".to_owned(), extractor::multiply_by_100),
        ("mta_tax".to_owned(), extractor::multiply_by_100),
        ("tip_amount".to_owned(), extractor::multiply_by_100),
        ("tolls_amount".to_owned(), extractor::multiply_by_100),
        ("ehail_fee".to_owned(), extractor::multiply_by_100),
        ("improvement_surcharge".to_owned(), extractor::multiply_by_100),
        ("total_amount".to_owned(), extractor::multiply_by_100),
        ("precipitation".to_owned(), extractor::multiply_by_1000),
        ("snow_depth".to_owned(), extractor::multiply_by_1000),
        ("snowfall".to_owned(), extractor::multiply_by_1000),
        ("average_wind_speed".to_owned(), extractor::multiply_by_1000),
    ]
}
