[package]
name = "locustdb-serialization"
version = "0.1.0"
edition = "2021"

[dependencies]
capnp = "0.19"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1"