// @generated by the capnpc-rust plugin to the Cap'n Proto schema compiler.
// DO NOT EDIT.
// source: disk_store/serialization/rust.capnp

pub mod name {
  pub const ID: u64 = 0xc2fe4c6d100166d0;
  pub fn get_type() -> ::capnp::introspect::Type { <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect() }
}
pub mod parent_module {
  pub const ID: u64 = 0xabee386cd1450364;
  pub fn get_type() -> ::capnp::introspect::Type { <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect() }
}
